; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		x16const.inc
;		Purpose:	Constants for x16 (Device)
;		Created:	25th April 2021
;		Author:		Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

KNLReadTimer = $FFDE
KNLPrintChar = $FFD2
KNLCheckKeyboarBuffer = $FFE4
KNLInputLine = $FFCF
KNLCheckBreak = $FFE1

KNLFileSetName = $FFBD
KNLFileSetLFS = $FFBA
KNLFileLoad = $FFD5
KNLFileSave = $FFD8