;
;	Automatically generated
;
	.include "main/01common.inc"
	.include "main/02macros.inc"
	.include "main/03data.inc"
	.include "main/imath/intmacros.inc"
	.include "main/main.inc"
	.include "assembler/assembler.inc"
	.include "device/device.inc"
	.include "error/error.inc"
	.include "floatingpoint/floatingpoint.inc"
	.include "generated/generated.inc"
	.include "interaction/interaction.inc"
	.include "string/string.inc"
	.include "tokeniser/tokeniser.inc"
	.include "main/main.asm"
	.include "assembler/assembler.asm"
	.include "device/device.asm"
	.include "error/error.asm"
	.include "floatingpoint/floatingpoint.asm"
	.include "generated/generated.asm"
	.include "interaction/interaction.asm"
	.include "string/string.asm"
	.include "tokeniser/tokeniser.asm"
