#!/bin/bash
#
#		Linux soak test. If you want to run this in DOS remove the while/done and change
#		comments to rem, call it doall.bat and put doall.bat on the end so it loops around.
#
while true; do
	make -B test TEST=testarr.py
	make -B test TEST=testarr2.py
	make -B test TEST=testbin.py
	make -B test TEST=testcore.py
	make -B test TEST=testprec.py
	make -B test TEST=teststrbin.py
	make -B test TEST=teststr.py
	make -B test TEST=testun.py
	make -B test TEST=testvar.py
done
